# specify the username on the host machine which you use to run the
# ansible-playbook
host_user: philip

home_path: /home/vagrant
git_crypt_repo_path: "{{ home_path }}/git-crypt"
node_js_repo_path: "{{ home_path }}/node"
update_etc_environment_path_script_path: /usr/local/bin/update-etc-environment-path
golang_bin_folder_path: /usr/local/go/bin
golang_tarball_path: "{{ home_path }}/go1.3.linux-amd64.tar.gz"
vagrant_password_file_dest_path: "{{ home_path }}/vagrant_password.txt"
dotfiles_repo_path: "{{ home_path }}/dotfiles"
vundle_repo_path: "{{ home_path }}/.vim/bundle/Vundle.vim"
my_id_rsa_pub_path: /tmp/my_id_rsa.pub
vagrant__append_id_rsa_pub_script_path: /usr/local/bin/append-id-rsa-pub-to-authorized-keys
local__append_id_rsa_pub_script_path: append-id-rsa-pub-to-authorized-keys.py
