# This is to allow for commands that require a password
- name: copy password file to Vagrant
  copy: src=vagrant_password.txt
        dest="{{vagrant_password_file_dest_path}}"
        owner=vagrant
        group=vagrant
        mode=0600

- name: apt-get update if last update was > 1h ago
  apt: update_cache=yes cache_valid_time=3600

- name: install zsh
  apt: name=zsh state=present

- name: install make
  apt: name=make state=present

- name: install curl
  apt: name=curl state=present

- name: install unzip
  apt: name=unzip state=present

- name: install sqlite3
  apt: name=sqlite3 state=present

- name: install socat
  apt: name=socat state=present

- name: install g++
  apt: name=g++ state=present

- name: install gdb
  apt: name=gdb state=present

- name: install valgrind
  apt: name=valgrind state=present

- name: install vim
  apt: name=vim state=present

- name: install screen
  apt: name=screen state=present

- name: install python-virtualenv
  apt: name=python-virtualenv state=present

- name: install python-dev
  apt: name=python-dev state=present

- name: install openjdk 7
  apt: name=openjdk-7-jdk state=present

- name: install mercurial
  apt: name=mercurial state=present

- name: check if Docker exists
  shell: command -v docker >/dev/null 2>&1
  register: docker_exists
  ignore_errors: true

- name: install Docker if it does not exist
  shell: (wget -qO- https://get.docker.io/ | bash) && usermod -aG docker vagrant
  when: docker_exists.rc != 0

- name: ensure git is not installed by package manager
  apt: name=git state=absent

- include: install_git.yml

- include: install_dotfiles.yml

- include: install_git_crypt.yml

- include: install_node_js.yml

- include: install_golang.yml

- include: install_rvm.yml

- name: remove password file
  shell: rm -f "{{vagrant_password_file_dest_path}}"
