- name: apt-get update if last update was > 1h ago
  apt: update_cache=yes cache_valid_time=3600

- name: install vim
  apt: name=vim state=present

- name: install screen
  apt: name=screen state=present
