- name: apt-get update if last update was > 1h ago
  apt: update_cache=yes cache_valid_time=3600

- name: install make
  apt: name=make state=present

- name: install curl
  apt: name=curl state=present

- name: install unzip
  apt: name=unzip state=present

- name: install sqlite3
  apt: name=sqlite3 state=present

- name: install socat
  apt: name=socat state=present

- name: install g++
  apt: name=g++ state=present

- name: install gdb
  apt: name=gdb state=present

- name: install valgrind
  apt: name=valgrind state=present

- name: install vim
  apt: name=vim state=present

- name: install screen
  apt: name=screen state=present

- name: install python-virtualenv
  apt: name=python-virtualenv state=present

- name: install python-dev
  apt: name=python-dev state=present

- name: install openjdk 7
  apt: name=openjdk-7-jdk state=present

- name: check if Docker exists
  shell: command -v docker >/dev/null 2>&1
  register: docker_exists
  ignore_errors: true

- name: install Docker if it does not exist
  shell: (wget -qO- https://get.docker.io/ | bash) && usermod -aG docker vagrant
  when: docker_exists.rc != 0

- include: install_git.yml

- include: install_git_crypt.yml

- include: install_node_js.yml

- include: install_golang.yml
